export const SET_USER = 'SET_USER'

export const SET_CHATROOMS = 'SET_CHATROOMS'
export const ADD_CHATROOM = 'ADD_CHATROOM'

export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM'

export const SET_MESSAGES = 'SET_MESSAGES'
export const ADD_MESSAGE = 'ADD_MESSAGE'

export const ADD_USER_TO_CHATROOM = 'ADD_USER_TO_CHATROOM'

export const SET_CHANNEL_LISTENING = 'SET_CHANNEL_LISTENING'